### ISSUE TITLE
Touch Issue with Telegram and QuickPic 

### ISSUE THREAD

**Issue by v7xda** [kerneltoast/android_device_oneplus_oneplus3#1]
Long press functions are triggered with normal tap.This happens on both Telegram and Whatsapp.Tried to grab a log,but seems like it's disabled Tried through adb and catlog but both couldn't read logs.

Here's a video depicting the issue:https://youtu.be/XY5mCLT4tqs

**Comment by kerneltoast** [comment]
Fixed: https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/5cf728623066dae1f5dbc6504adf9ee8a5be4dce
