### ISSUE TITLE
WeChat fingerprint payment

### ISSUE THREAD

**Issue by shouhu1993** [kerneltoast/android_device_oneplus_oneplus3#4]
hi sultanxda,how about add WeChat fingerprint payment from lineage commit? would you plan to support it?

**Comment by FraEgg** [comment]
Hello,
i have a commit for this in my sultanxda device tree ;-)

https://github.com/FraEgg/android_device_oneplus_oneplus3_sultanxda/commit/fafa1613553fb1ea48583ea63be9d019120bf32d

My RR-builds now support WeChat fingerprint payment.

Cu Frank

**Comment by shouhu1993** [comment]
@FraEgg i flashed it. but touch was very buggy.

**Comment by FraEgg** [comment]
@shouhu1993 : i have merge this from lineageos device sources. please send me more information about your problem.

**Comment by shouhu1993** [comment]
@FraEgg sorry....it is not WeChat fingerprint payment problem. 
after i flashed your rom. when i swipe up or down, the screen seem stop working or react slowly so i should try several times. it is very annoying. now i restore sultan's rom.
by the way, i use 4.5.1 frimware.
sorry for my bad english.
